### ISSUE TITLE
Unable to get zipkin metrics out

### ISSUE THREAD

**Issue by isovector** [kim/opentracing#1]
Hi there, I'm attempting to send instrumentation out to zipkin.

```haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Control.Monad.IO.Class
import Control.Monad
import Control.Concurrent
import           OpenTracing
import qualified OpenTracing as OT
import qualified OpenTracing.Log as OT
import qualified OpenTracing.Zipkin as Z
import qualified OpenTracing.Zipkin.HttpReporter as ZR

zipkinTracing :: MonadIO m => OT.Sampler -> m (OT.Tracing Z.ZipkinContext MonadIO)
zipkinTracing sampler = do
  let endpoint = ZR.Endpoint (Just "myservice") (Just $ read "localhost") Nothing (Just 9411)
  env <- Z.newEnv sampler
  renv <- liftIO $ ZR.newEnv ZR.V2 endpoint "localhost" 9411 OT.jsonMap
  pure $ OT.Tracing (Z.zipkinTracer env) (ZR.zipkinHttpReporter renv)

main :: IO ()
main = do
  tracing <- zipkinTracing $ constSampler True
  forM_ [0..1000] . const $ traced' tracing (spanOpts "hello" mempty) $ \x -> putStrLn "hello" >> threadDelay 500000
```

I started zipkin via the quickstart guide:

```bash
wget -O zipkin.jar 'https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec'
java -jar zipkin.jar
```

and it is running on `localhost:9411`.

Any suggestions for how to continue? Thanks!

**Comment by isovector** [comment]
To clarify, no traces are showing up in zipkin. I've forked the repo and removed the silent error handling, but nothing seems to happen.

**Comment by kim** [comment]
Uh oh, you are a little bit early here, things aren’t yet to be expected in a usable state 8)

That said, thanks for reporting, I’ll have a look asap.

**Comment by isovector** [comment]
Yeah, I figured I might be on the early train here but we've got a need and the library looked like it was most of the way there. I'm more than willing to contribute if you could use a hand. I'm planning on doing more investigation today -- will report back with any findings.

**Comment by kim** [comment]
Additionally, you'll need to replace `read "localhost"` with `read "127.0.0.1"`.

**Comment by kim** [comment]
So yeah, this needs quite some work until it's usable for anything usable (eg. error handling, logging, perhaps metrics). As the spec is quite, ahem, low on details, it's been quite a bit of staring-at-Go-code-and-faithfully-transliterate-to-Haskell so far. Happy to take contributions or just issues, but expect things to change in breaking ways!

**Comment by isovector** [comment]
That fixes it! Thanks!!
