### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by t3hmrman** [kim/opentracing#11]
Hey I'm in the middle of trying to get opentracing (using Jaeger) working with a small [Servant](https://github.com/haskell-servant/servant) based API I'm writing. 

I'd like to use your library, but am not sure what the license is, would you mind setting one on the repository?

**Comment by kim** [comment]
It's all Apache 2 (the sub-packages have a LICENSE file).

> setting one on the repository

Not sure what you mean by that- is this a github feature?

**Comment by t3hmrman** [comment]
Oh sorry I didn't check them individually, I was expecting a LICENSE file at the top level, my apologies

**Comment by kim** [comment]
True, should probably symlink to a top level file. Noted.

**Comment by t3hmrman** [comment]
Absolutely no problem --  I'm digging into the code now, thanks for writing the library! Looking forward to being able to get some data sent to my Jaeger instance
