### ISSUE TITLE
Hackage release 

### ISSUE THREAD

**Issue by benweitzman** [kim/opentracing#22]
Is there a roadmap for a Hackage release?

I’m using this library in another library I’m developing that integrates polysemy’s free monad architecture with distributed tracing. 

I’d love to help out in any way that I can to get this ready for release. It’s a really great project that I think a lot of people will benefit from!

**Comment by kim** [comment]
Sounds like a plan. 

I’d expect setting up a proper integration test harness will be the biggest chunk of work, so  I’d personally prioritise generated types. But either is good for getting things out there :)

**Comment by kim** [comment]
I cannot say that I'm actively maintaining this, in particular I haven't been
following the OpenTelemetry initiative. I'm also not using any tracer
day-to-day, so am unlikely to notice changes or opportunities for improvement.
I'd be okay with publishing and subsequently maintaining the core lib, but am
definitely lacking time to make sure all the different backends continue to
work.

From the occasional contributions and comments here I can tell that _someone_
must be using this library. Maybe people could chime in here and share which
backend(s) they're using? Perhaps there's even interest in (co-)maintainership?

**Comment by mjrussell** [comment]
SimSpace is probably the most active on this repo so far. We've also built some middleware on top of this that we should probably open source some point soon. Maybe we would be a good co-maintainer? @jship, @peterbecich, and myself all have contributions to this library and we are quite happy with it at SimSpace

**Comment by mjrussell** [comment]
@benweitzman also seems pretty interested having started the issue and laid out a plan so I don't want to steal his thunder!

**Comment by coderfromhere** [comment]
> Maybe people could chime in here and share which
backend(s) they're using? 

I'm interested in `opentracing` and `opentracing-wai` with Jaeger backend and `ot-` propagators in particular, having the packages on Hackage would simplify Nix pipelines.

**Comment by kim** [comment]
I'm putting in a bit of time to prep things up. A few questions for y'all:

* Is `stack` still a thing?
* Would anyone mind dropping Zipkin V1 support? Thrift is a bit of a gnarly dependency.
* Would anyone mind dropping Google CloudTrace support? I don't really have ways to test it, and pinning to an old version of both the API and `gogol` seems to be a pain in the neck.

**Comment by kim** [comment]
> dropping Zipkin V1 support

Ah nevermind, jaeger also wants thrift

**Comment by kim** [comment]
We're almost there, but Hackage complains that the package already exists. Yet https://hackage.haskell.org/package/opentracing returns 404.

Anyone a clue what is going on?

**Comment by kirelagin** [comment]
The package indeed already exists: someone uploaded a candidate for it and thus became the owner of the name:

https://hackage.haskell.org/package/opentracing-0.1.0.0/candidate

I believe the only thing that can be done now is contacting this person and asking them to make you a maintainer: https://hackage.haskell.org/package/opentracing/maintainers/.

**Comment by kirelagin** [comment]
Ok, I believe that was @emilypi.

**Comment by alexbiehl** [comment]
Looks like ownership has been transferred! 🎉

**Comment by kim** [comment]
Version 0.1.0.0 uploaded to hackage :rocket: 

Thanks everyone for your patience and persistent nagging :) Thanks @emilypi for transferring ownership.
