### ISSUE TITLE
stdTracer thread safety

### ISSUE THREAD

**Issue by jship** [kim/opentracing#24]
The `stdTracer` in `OpenTracing.Standard` is built using a `StdEnv`, and the `envPRNG` field in `StdEnv` is a `GenIO`.

`GenIO` isn't thread-safe unfortunately: https://hackage.haskell.org/package/mwc-random-0.14.0.0/docs/System-Random-MWC.html#t:Gen

We noticed issues in tests that concurrently start up traces using the same `Tracer` where the resulting finished spans would occasionally have incorrect parent/child references due to the IDs being duplicated.

SimSpace has made the `GenIO` access thread-safe in this commit - https://github.com/Simspace/opentracing/commit/43ba8fd415562281e087d1d7a5b300bbd9d9837a - and our tests are working great.  We're happy to upstream this fix as well.

**Comment by kim** [comment]
Ah good catch!

I notice you have other changes in that branch -- do you want to submit a rebased PR, or should I just cherry-pick the commit?

**Comment by jship** [comment]
Cherry-picking sounds great.  Thanks for your work on the lib!

**Comment by kim** [comment]
e2bbb30f17e432e2f39e300d73f1d0cb818be8dd
