### ISSUE TITLE
OpenTracing vs OpenTelemetry

### ISSUE THREAD

**Issue by obfuscated-developer** [kim/opentracing#43]
According to [opentracing.io](https://opentracing.io) the OpenTracing project is now archived and OpenTelemetry is the new version of that. Is the [opentracing](https://hackage.haskell.org/package/opentracing) package compatible with OpenTelemetry?

**Comment by kim** [comment]
I understood that OpenTelemetry is essentially a superset of OpenTracing. It
might be that the former has evolved since, but I haven't checked. If there a
compatibility issues, perhaps they can be fixed by providing a new reporter?

**Comment by obfuscated-developer** [comment]
After going through the code, it does look like adding a new reporter should do the trick. Though I'm still in the process of investigating atm. I'll try to remember to update this issue once I have more data

**Comment by obfuscated-developer** [comment]
UPD: OpenTelemetry collectors can receive data in Jaeger format, so I could re-use most of the `opentracing` and `opentracing-jaeger` stuff. However, the collector didn't work until I specified the request content type in the request header, so I had to rewrite a couple of things

```
newJaegerCollector :: Otel.JaegerCollectorOptions -> IO Otel.JaegerCollector
newJaegerCollector opt = do
  rq <- mkReq
  -- Otel.JaegerCollector is a newtype but the module where it's defined doesn't
  -- expose the constructor, so I had to use unsafeCoerce to make this work
  fmap Coerce.unsafeCoerce
    . Otel.newBatchEnv
    . Lens.set Otel.boptErrorLog (opt ^. Otel.jcoErrorLog) . Otel.batchOptions
    $ reporter (opt ^. Otel.jcoManager) (opt ^. Otel.jcoErrorLog) rq tproc
  where
    mkReq = do
      rq <-
        Client.parseRequest
          $ "http://" <> Lens.view (Otel.jcoAddr . Otel.addrHostName) opt
          <> ":"
          <> show (Lens.view (Otel.jcoAddr . Otel.addrPort) opt)
          <> "/api/traces?format=jaeger.thrift"
      pure rq
        { Client.method = "POST"
        , Client.secure = Lens.view (Otel.jcoAddr . Otel.addrSecure) opt
        , Client.requestHeaders
            = ("Content-Type", "application/x-thrift") : Client.requestHeaders rq
        }

    tproc = Otel.toThriftProcess (opt ^. Otel.jcoServiceName) (opt ^. Otel.jcoServiceTags)
```

It works now but it would be nice if the header was set by the library so that it can be used out of the box

**Comment by kim** [comment]
Thanks for investigating. Let me know if #44 works for you
