### ISSUE TITLE
Release 0.2.3 to hackage?

### ISSUE THREAD

**Issue by ArturGajowy** [kim/opentracing#51]
Hi!

I'm a happy user of your library (thanks!) who'd like to migrate to GHC 9.4 and 9.6.
Are you planning releasing the current master to Hackage in the near future? :)

Thanks!

**Comment by kim** [comment]
Apologies, I have been a little lazy with this lately. 0.3.0 is now up on Hackage.

**Comment by ArturGajowy** [comment]
No worries, and thank you! :)
